Repository blaccsmith/website, pull requests merged in 2021-09, with the labels that each got.

#33 Created page to showcase all blogs
  blogs/from-backend-to-ux.mdx
  components/atoms/BlogPreview.tsx
  components/atoms/ProgressiveImage.tsx
  package.json
  pages/blog/index.tsx
  theme.ts
  types.ts
  yarn.lock
Labels: Ready to review

#19 Creating sandbox to preview blogs
  .github/BLOG_CONTRIBUTING.md
  blogs/example.mdx
  blogs/from-backend-to-ux.mdx
  blogs/getting-started-with-crypto.mdx
  components/atoms/Blockquote.tsx
  components/atoms/Layout/Footer.tsx
  components/atoms/Layout/Header.tsx
  components/atoms/Layout/index.tsx
  components/atoms/ScrollToTop.tsx
  components/molecules/AuthorInfo.tsx
  components/molecules/BlogHeader.tsx
  mdx/components.tsx
  next.config.js
  package.json
  pages/blog/[slug].tsx
  public/blogs/from-backend-to-ux/avi.jpeg
  public/blogs/getting-started-with-crypto/avi.jpeg
  public/blogs/getting-started-with-crypto/coins.png
  public/blogs/getting-started-with-crypto/digital-wallet.png
  public/blogs/getting-started-with-crypto/hardware-wallet.png
  public/blogs/getting-started-with-crypto/one-united-bank.png
  public/blogs/getting-started-with-crypto/trending-searches.png
  public/github-empty-folder.png
  types.ts
  yarn.lock
Labels: In Progress

#43 Created code block component for rendering
  blogs/example.mdx
  mdx/components.tsx
  package.json
  yarn.lock
Labels: 📋 Ready to review

#44 refactor: added copy button to code block
  mdx/components.tsx
Labels: 📋 Ready to review
