Repository blaccsmith/website, pull requests merged in 2021-08, with the labels that each got.

#2 Initial nextjs scaffold
  .eslintrc.js
  .eslintrc.json
  .gitignore
  .prettierrc
  README.md
  next-env.d.ts
  next.config.js
  package.json
  pages/_app.tsx
  pages/index.tsx
  public/favicon.ico
  public/vercel.svg
  styles/Home.module.css
  styles/globals.css
  tsconfig.json
  yarn.lock
Labels: good first issue

#16 Added new issue template
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/feature-request.yaml
Labels: In Progress

#12 Adding Figma styling to Chakra
  components/atoms/Layout/Footer.tsx
  components/atoms/Layout/Header.tsx
  components/atoms/Layout/index.tsx
  package.json
  pages/_app.tsx
  theme.ts
  yarn.lock
Labels: good first issue, Needs revision
